#spring:
#  datasource:
#    driver-class-name: com.p6spy.engine.spy.P6SpyDriver
#    url: jdbc:p6spy:mysql://192.168.101.142:3306/mp?serverTimezone=Asia/Shanghai&characterEncoding=utf8&useUnicode=true&useSSL=false
#    username: root
#    password: abc123
#  main:
#    banner-mode: off
spring:
  datasource:
    dynamic:
      primary: master #\u8BBE\u7F6E\u9ED8\u8BA4\u7684\u6570\u636E\u6E90\u6216\u8005\u6570\u636E\u6E90\u7EC4,\u9ED8\u8BA4\u503C\u5373\u4E3Amaster
      strict: false #\u4E25\u683C\u5339\u914D\u6570\u636E\u6E90,\u9ED8\u8BA4false. true\u672A\u5339\u914D\u5230\u6307\u5B9A\u6570\u636E\u6E90\u65F6\u629B\u5F02\u5E38,false\u4F7F\u7528\u9ED8\u8BA4\u6570\u636E\u6E90
      datasource:
        master:
          url: jdbc:p6spy:mysql://192.168.101.142:3306/mp?serverTimezone=Asia/Shanghai&characterEncoding=utf8&useUnicode=true&useSSL=false
          username: root
          password: abc123
          driver-class-name: com.p6spy.engine.spy.P6SpyDriver # 3.2.0\u5F00\u59CB\u652F\u6301SPI\u53EF\u7701\u7565\u6B64\u914D\u7F6E
        slave_1:
          url: jdbc:p6spy:mysql://192.168.101.142:3306/mp2?serverTimezone=Asia/Shanghai&characterEncoding=utf8&useUnicode=true&useSSL=false
          username: root
          password: abc123
          driver-class-name: com.p6spy.engine.spy.P6SpyDriver

